Insert into LOCAL.BEVERAGE_MEMBER (IDENTIFICATION_NO,PASSWORD,CUSTOMER_NAME,STATUS) values ('A124243295','123','Jay','1');
Insert into LOCAL.BEVERAGE_MEMBER (IDENTIFICATION_NO,PASSWORD,CUSTOMER_NAME,STATUS) values ('D201663865','123','Tiffany','1');
Insert into LOCAL.BEVERAGE_MEMBER (IDENTIFICATION_NO,PASSWORD,CUSTOMER_NAME,STATUS) values ('J213664153','123','Jolin','1');
Insert into LOCAL.BEVERAGE_MEMBER (IDENTIFICATION_NO,PASSWORD,CUSTOMER_NAME,STATUS) values ('F126873254','123','Rita','1');
Insert into LOCAL.BEVERAGE_MEMBER (IDENTIFICATION_NO,PASSWORD,CUSTOMER_NAME,STATUS) values ('G436565447','123','Wendy','1');
Insert into LOCAL.BEVERAGE_MEMBER (IDENTIFICATION_NO,PASSWORD,CUSTOMER_NAME,STATUS) values ('1','1','Max','1');
commit;