Insert into LOCAL.BEVERAGE_ORDER_DETAIL (ORDER_DETAIL_ID,BUY_QUANTITY,GOODS_BUY_PRICE,GOODS_ID,ORDER_ID) values (1,2,100,1,1);
Insert into LOCAL.BEVERAGE_ORDER_DETAIL (ORDER_DETAIL_ID,BUY_QUANTITY,GOODS_BUY_PRICE,GOODS_ID,ORDER_ID) values (2,3,20,3,1);
Insert into LOCAL.BEVERAGE_ORDER_DETAIL (ORDER_DETAIL_ID,BUY_QUANTITY,GOODS_BUY_PRICE,GOODS_ID,ORDER_ID) values (3,1,7,2,1);
commit;